### ISSUE TITLE
Github to Gantt

### ISSUE THREAD

**Issue by NinaTanneberger** [NinaTanneberger/studio3#14]
Discuss with facilitator the installation of Github plugins so that I can use a Gantt chart for my project. I need assistance as I have never used something like this.

https://github.com/realm/github-gantt

**Comment by rhaubt** [comment]
The repository you looked at seems to not be maintained and has some bugs.

Much easier way to do this is to use eg https://live.ganttlab.org/

- go to https://live.ganttlab.org/
- got to GitHub > click on your profile in the top left corner > settings > Developer Settings > generate token > select what you want the key to have access to eg only repo stats and reports
- use the token to log into https://live.ganttlab.org/

I uploaded a screenshot to your repository [root folder > lecturer_comments > ganttchart_using_ganttlablive.png](https://github.com/NinaTanneberger/studio3/blob/master/lecturer_comments/ganttchart_using_ganttlablive.png). It works really well and is I think exactly what you are looking for.

**Comment by NinaTanneberger** [comment]
Yeah it works, but only shows each issue with a 24 hour window instead of coinciding with the milestones.

![image](https://user-images.githubusercontent.com/43361725/52453218-088a1f00-2b92-11e9-8f2b-8268ba41ae47.png)

**Comment by rhaubt** [comment]
The hours should extend once the project reached more than 24 hours.

Otherwise have a look at this project. You need node.js.
https://github.com/neyric/gh-issues-gantt

**Comment by NinaTanneberger** [comment]
That makes sense.

I've never installed things like this successfully - I tried with several Github APIs during the last project. Maybe I will just go through it with you during class.

Maybe installing Github APIs can be one of the things we discuss during lectures in our last weeks of the trimester.

**Comment by NinaTanneberger** [comment]
Abandoned due to it not doing what I want it to do.
