### ISSUE TITLE
Can't Login IWP

### ISSUE THREAD

**Issue by NinaTanneberger** [NinaTanneberger/studio3#18]
This seems really obsurd, but I can't figure out how to sign in to my WordPress Admin. 

I have installed **Instant Word Press** to my `htdocs` folder, can get the **WordPress Frontpage** working but when I try to login to the admin it says wrong password.

I have tried different combinations, I have looked at **MySQL Admin** for users as well and no luck.

I know I have logged in in the past so it's likely something hiding in my machine that is causing the issue. It has been a while since I have used **IWP** - over a year. I know the answer is probably something very basic.

This is on my PC so I will attempt to get it working on my laptop and maybe that will work. Otherwise I will bring my laptop into class on Wednesday for a review.

**Comment by rhaubt** [comment]
Make sure to follow the steps that I sent you earlier when installing WP.
https://codex.wordpress.org/Installing_WordPress

Check the sections on Creating a New User when you create the database.

You should be able to use the Admin password and username you used for your database to log in as a superuser. Otherwise check the User table and create a new user phpMyAdmin (also see the link I sent you earlier today).

Alternatively check the section on resetting your password here https://codex.wordpress.org/Resetting_Your_Password

**Comment by NinaTanneberger** [comment]
Wow. I forgot to create a database. Will log my findings once I've gone through it again.

**Comment by NinaTanneberger** [comment]
Ok so now I am confused. Like I said I haven't used Wordpress in a while so bear with me.. Should I be using **InstantWordpress** or just **Wordpress**?

**Comment by rhaubt** [comment]
1. Wordpress.com
The online version of Wordpress. You have no access to the backend or server.

2. Instant Wordpress:
Advantage is that you do not need WAMP or another server application. Instant Wordpress runs a Linux Server at startup and simulates an FTP server. The biggest advantage is that you can run it on a memory stick - plug and play. This is easy to use but you might run into some problems when trying to run updates and / or moving the Wordpress installation and database to a live server.

3. Wordpress.org
Download and install your own version of Wordpress. This gives you the highest level of flexibility. You need to download the Wordpress package from wordpress.org or GitHub and run eg WAMP with php and MySQL.
Once you download Wordpress you need to follow the instructions to install it on your local host. This includes that you need to set up a database. For the database setup you can use eg phpMyAdmin.

**Comment by NinaTanneberger** [comment]
Wonderful. Thanks Rob!
